/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import com.mysql.cj.jdbc.Blob;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import static javaapplication1.Doc_popup.S_degr;
import static javaapplication1.Doc_popup.S_desig;
import static javaapplication1.Doc_popup.S_doc;
import static javaapplication1.Doc_popup.S_img;
import static javaapplication1.Doc_popup.S_num;
import static javaapplication1.Doc_popup.S_uni;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import project.ConnectionProvider;

/**
 *
 * @author Tanvir
 */
public class Forget_Password extends javax.swing.JFrame {

    /**
     * Creates new form Forget_Password
     */
    public Forget_Password() {
        initComponents();
        setBackground(new Color(0,0,0,98));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Num_field = new javax.swing.JTextField();
        New_Password_field = new javax.swing.JTextField();
        NID_field = new javax.swing.JTextField();
        set_new_password = new javax.swing.JButton();
        Conf_Password_fild = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(null);

        Num_field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Mobile no.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(Num_field);
        Num_field.setBounds(580, 290, 240, 40);

        New_Password_field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Set New Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        New_Password_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                New_Password_fieldActionPerformed(evt);
            }
        });
        getContentPane().add(New_Password_field);
        New_Password_field.setBounds(580, 370, 240, 40);

        NID_field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "NID no.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(NID_field);
        NID_field.setBounds(580, 330, 240, 40);

        set_new_password.setBackground(new java.awt.Color(29, 180, 254));
        set_new_password.setFont(new java.awt.Font("Montserrat SemiBold", 0, 13)); // NOI18N
        set_new_password.setForeground(new java.awt.Color(255, 255, 255));
        set_new_password.setText("Update");
        set_new_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_new_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(set_new_password);
        set_new_password.setBounds(660, 465, 160, 30);

        Conf_Password_fild.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Confirm Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        getContentPane().add(Conf_Password_fild);
        Conf_Password_fild.setBounds(580, 410, 240, 40);

        jButton1.setBackground(new java.awt.Color(29, 180, 254));
        jButton1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 13)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 465, 70, 30);

        jLabel2.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(827, 290, 10, 18);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/All_Dashboard_Image/Setting_pic.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 280, 490, 230);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void New_Password_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_New_Password_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_New_Password_fieldActionPerformed

    private void set_new_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_new_passwordActionPerformed
         String mobile = Num_field.getText();
        String NID = NID_field.getText();
        String newPassword = New_Password_field.getText();
        String confirmPassword = Conf_Password_fild.getText();

        if (newPassword.equals(confirmPassword)) {
            try {
                Connection conn = ConnectionProvider.getCon();
                Statement st = conn.createStatement();

                // Check if the mobile number and NID number match with the database
                ResultSet rs = st.executeQuery("select * from signup where mobile = '" + mobile + "' and NID ='" + NID + "'");
                if (rs.next()) {
                    // Update the password in the database
                    st.executeUpdate("update signup set pass = '" + newPassword + "' where mobile = '" + mobile + "' and NID ='" + NID + "'");

                    // Show a success message
                    JOptionPane.showMessageDialog(null, "Successfully updated password!");
                } else {
                    // Show an error message
                    JOptionPane.showMessageDialog(null, "No details found");
                }
            } catch (Exception e) {
                // Handle the exception
                e.printStackTrace();
            }
        } else {
            // Show an error message
            JOptionPane.showMessageDialog(null, "New password and confirm password do not match");
        }
        
        
    }//GEN-LAST:event_set_new_passwordActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new Login().setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forget_Password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forget_Password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Conf_Password_fild;
    private javax.swing.JTextField NID_field;
    private javax.swing.JTextField New_Password_field;
    private javax.swing.JTextField Num_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton set_new_password;
    // End of variables declaration//GEN-END:variables
}
