/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;
import static javaapplication1.Ambulance.My_Name_Set8;
import static javaapplication1.Ambulance.My_Pic8;
import static javaapplication1.Dashboard1.loginName1;
import static javaapplication1.Dashboard1.myimg;
import static javaapplication1.Doctor.My_Image2;
import static javaapplication1.Doctor.My_Pic2;
import static javaapplication1.Lab_Report.My_Name_Set6;
import static javaapplication1.Lab_Report.My_Pic6;
import static javaapplication1.MedicineInfo.My_Name_Set7;
import static javaapplication1.MedicineInfo.My_Pic7;
import static javaapplication1.Patients_List.My_Name_Set3;
import static javaapplication1.Patients_List.My_Pic3;
import static javaapplication1.Payment.My_Name_Set9;
import static javaapplication1.Payment.My_Pic9;
import static javaapplication1.Prescription_Find.My_Name_Set5;
import static javaapplication1.Prescription_Find.My_Pic5;
import static javaapplication1.Seat_Booking.My_Name_Set4;
import static javaapplication1.Seat_Booking.My_Pic4;


/**
 *
 * @author Tanvir
 */
public class Profile extends javax.swing.JFrame {

    /**
     * Creates new form Profile
     */
    public Profile() {
        initComponents();


        
    
    

   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(228, 283));
        setMinimumSize(new java.awt.Dimension(228, 283));
        setUndecorated(true);
        getContentPane().setLayout(null);

        Data_Name.setFont(new java.awt.Font("Montserrat SemiBold", 0, 14)); // NOI18N
        Data_Name.setForeground(new java.awt.Color(29, 180, 254));
        Data_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Data_Name.setText("Tanvir");
        getContentPane().add(Data_Name);
        Data_Name.setBounds(40, 180, 170, 30);

        Data_Image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication1/profileImages/tanvirImg.png"))); // NOI18N
        getContentPane().add(Data_Image);
        Data_Image.setBounds(76, 52, 110, 110);

        set_from_myDatabase.setText("Set ");
        set_from_myDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                set_from_myDatabaseActionPerformed(evt);
            }
        });
        getContentPane().add(set_from_myDatabase);
        set_from_myDatabase.setBounds(50, 240, 72, 23);

        Cart_Acrive.setText("jButton1");
        Cart_Acrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cart_AcriveActionPerformed(evt);
            }
        });
        getContentPane().add(Cart_Acrive);
        Cart_Acrive.setBounds(200, 230, 75, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void set_from_myDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_set_from_myDatabaseActionPerformed
        // TODO add your handling code here:
        myimg.setIcon(Data_Image.getIcon());
        loginName1.setText(Data_Name.getText());
        
        My_Image2.setText(loginName1.getText());
        My_Pic2.setIcon(myimg.getIcon());
        
        My_Pic3.setIcon(myimg.getIcon());
        My_Name_Set3.setText(loginName1.getText());
        
        My_Pic4.setIcon(myimg.getIcon());
        My_Name_Set4.setText(loginName1.getText());
        
        My_Pic5.setIcon(myimg.getIcon());
        My_Name_Set5.setText(loginName1.getText());
        
        My_Pic6.setIcon(myimg.getIcon());
        My_Name_Set6.setText(loginName1.getText());
        
        My_Pic7.setIcon(myimg.getIcon());
        My_Name_Set7.setText(loginName1.getText());
        
        My_Pic8.setIcon(myimg.getIcon());
        My_Name_Set8.setText(loginName1.getText());
        
        My_Pic9.setIcon(myimg.getIcon());
        My_Name_Set9.setText(loginName1.getText());
        
    }//GEN-LAST:event_set_from_myDatabaseActionPerformed
    Cart cartFrame = new Cart();
    private void Cart_AcriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cart_AcriveActionPerformed
        // TODO add your handling code here:
        cartFrame.setVisible(true);
        cartFrame.setExtendedState(Cart.ICONIFIED);
        
    }//GEN-LAST:event_Cart_AcriveActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static final javax.swing.JButton Cart_Acrive = new javax.swing.JButton();
    public static final javax.swing.JLabel Data_Image = new javax.swing.JLabel();
    public static final javax.swing.JLabel Data_Name = new javax.swing.JLabel();
    public static final javax.swing.JButton set_from_myDatabase = new javax.swing.JButton();
    // End of variables declaration//GEN-END:variables
}
